inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - graphql/*
  Exclude:
    - db/schema.rb
    - bin/*
Style/FrozenStringLiteralComment:
  Enabled: false
